version: "3.8"

services:
  database:
    image: postgres:15
    container_name: directus_db
    restart: always
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: directus
    volumes:
      - pgdata:/var/lib/postgresql/data

  directus:
    image: directus/directus:latest
    container_name: directus_app
    restart: always
    ports:
      - "8055:8055"
    env_file:
      - .env
    environment:
      DB_CLIENT: pg
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: ${DB_PASSWORD}
      WEBSOCKETS_ENABLED: "true"
    depends_on:
      - database

volumes:
  pgdata:
